return {
  {
    "mason-org/mason-lspconfig.nvim",
    dependencies = {
      {
        "mason-org/mason.nvim",
        opts = {
          ui = {
            icons = {
              package_installed = "✓",
              package_pending = "➜",
              package_uninstalled = "✗",
            },
          },
        },
      },
      "neovim/nvim-lspconfig",
    },
    opts = {
      ensure_installed = {
        "astro",
        "bashls",
        "csharp_ls@0.16",
        "cssls",
        "docker_compose_language_service",
        "dockerls",
        "gopls",
        "gradle_ls",
        "graphql",
        "html",
        "jdtls",
        "lwc_ls",
        "jqls",
        "jsonls",
        "kotlin_language_server",
        "lemminx",
        "lua_ls",
        "marksman",
        "prismals",
        "pylyzer",
        "rust_analyzer",
        "sqlls",
        "svelte",
        "tailwindcss",
        "terraformls",
        "vtsls",
        "yamlls",
        "zls",
      },
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = {
      ensure_installed = {
        "biome",
        "black",
        "csharpier",
        "gofumpt",
        "goimports-reviser",
        "golines",
        "google-java-format",
        "isort",
        "ktlint",
        "markdownlint",
        "mdformat",
        "prettier",
        "pyink",
        "rustywind",
        "stylua",

        "gitlint",
        "hadolint",
        "ktlint",
        "markdownlint",
        "mypy",
        "pylint",
        "revive",
        "staticcheck",
        "stylelint",
        "tfsec",
        "yamllint",
        "prettier",
        "stylua",
      },
    },
    dependencies = {
      "mason-org/mason.nvim",
      { "folke/lazydev.nvim", opts = {} },
    },
  },
}
